# Utilisation de l'image de base adoptopenjdk avec l'architecture Linux x86_64
FROM adoptopenjdk/openjdk11:alpine

# Définition du répertoire de travail dans le conteneur
WORKDIR /app

# Copie du fichier JAR de l'application dans le conteneur
COPY build/libs/*.jar app.jar

# Exposition du port sur lequel l'application Quarkus écoute (par défaut : 8080)
EXPOSE 8080

# Commande pour démarrer l'application lorsque le conteneur démarre
CMD ["java", "-jar", "app.jar"]
